###

http://localhost:8080/orders/users/6
Content-Type: application/json

{
  "description": "First Order"
}

###
POST http://localhost:8080/order/1/items
Content-Type: application/json
Accept: application/json

{
  "productName": "Case",
  "quantity": 1,
  "price": 1999.00
}
###
GET http://localhost:8080/order/1

###
GET http://localhost:8080/orders/user/6/orders/paged?page=0&size=2&sortBy=user_id

###
POST http://localhost:8080/order/2/addProduct/1

###
GET http://localhost:8080/order/2










