#############################################
# Base Configuration
#############################################

@baseUrl = http://localhost:8080
@jwt_token = eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJOZXciLCJpYXQiOjE3NjU5NzY2OTAsImV4cCI6MTc2NTk4MDI5MH0.c-ST1-njgxvQ3kwBnI89Rw4MBwKcTzHCsd22V5gixNs

############################################
GET http://localhost:8080/order/ping
Authorization: Bearer {{jwt_token}}
############################################
#############################################
# 1️⃣ CREATE ORDER (Authenticated User)
#############################################

POST {{baseUrl}}/order
Content-Type: application/json
Authorization: Bearer {{jwt_token}}

{
  "description": "First Order"
}

###
#############################################
# 2️⃣ ADD ITEM TO ORDER
#############################################

POST {{baseUrl}}/order/1/items
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{jwt_token}}

{
  "productName": "Case",
  "quantity": 1,
  "price": 1999.00
}

###
#############################################
# 3️⃣ GET SINGLE ORDER (Ownership enforced)
#############################################

GET {{baseUrl}}/order/1
Authorization: Bearer {{jwt_token}}

###
#############################################
# 4️⃣ GET LOGGED-IN USER ORDERS (PAGED)
#############################################

GET {{baseUrl}}/order/my?page=0&size=2&sortBy=id
Authorization: Bearer {{jwt_token}}

###
#############################################
# 5️⃣ ADD PRODUCT TO ORDER
#############################################

POST {{baseUrl}}/order/2/addProduct/1
Authorization: Bearer {{jwt_token}}

###
#############################################
# 6️⃣ GET ORDER AFTER PRODUCT ADD
#############################################

GET {{baseUrl}}/order/2
Authorization: Bearer {{jwt_token}}
