create table alien(
    id int primary key,
    name varchar(20),
    email varchar(50)
);

CREATE TABLE users (
   id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
   name VARCHAR2(50),
   age INTEGER
);
