GET http://localhost:8080/hello
###
GET http://localhost:8080/hello/Nitesh

###
POST http://localhost:8080/userJPA
Content-Type: application/json

{
  "name": "Ram Verma",
  "age": 25
}
###
GET http://localhost:8080/userJPA


###
GET http://localhost:8080/userJPA/3

###
PUT http://localhost:8080/userJPA/3
Content-Type: application/json

{
  "name": "Nitesh Singh",
  "age": 30
}

###
POST http://localhost:8080/order/user/3
Content-Type: application/json

{
  "description": "third Order"
}

###
GET http://localhost:8080/users/search?name=Nitesh Singh


###
GET http://localhost:8080/users/searchNameContaining?name=Singh

###
GET http://localhost:8080/users/searchByAge?minAge=18&maxAge=30

###
GET http://localhost:8080/users/searchAboveAge?age=20







