GET http://localhost:8080/hello
###
GET http://localhost:8080/hello/Nitesh

###
POST http://localhost:8080/userJPA
Content-Type: application/json

{
  "name": "",
  "age": 25
}
###
GET http://localhost:8080/userJPA


###
GET http://localhost:8080/userJPA/77

###
PUT http://localhost:8080/userJPA/7
Content-Type: application/json

{
  "name": "UpdatedName",
  "age": 30
}

###
DELETE http://localhost:8080/userJPA/5

